# NEBULA-QUANT v1 | nq_paper config — safe defaults

DEFAULT_PAPER_INITIAL_CAPITAL: float = 100_000.0
DEFAULT_MAX_PAPER_POSITIONS: int = 10
DEFAULT_PAPER_COMMISSION: float = 0.0
DEFAULT_PAPER_SLIPPAGE_BPS: float = 10.0
